spring:
  datasource:
    username: root
    password: 552310
    url: jdbc:mysql://111.231.54.84:3306/antiesys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false



mybatis:
  mapper-locations: classpath:mapper/*.xml
